---
language: ruby
sudo: false
bundler_args: --without development
before_install:
  - rm Gemfile.lock || true
  - gem update bundler
rvm:
  - 2.0.0
  - 2.1.0
script: bundle exec rake test --trace
env:
  - PUPPET_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
